-- create table cars
-- (
--     id int generated by default as identity,
--     manufacturer varchar(30) not null check (manufacturer <> ''),
--     name varchar(30) not null check (length(name) > 0),
--     volume float not null,
--     creationDate int,
--     color varchar(30) default 'white',
--     type varchar(30) not null
--
-- );

-- insert into cars (manufacturer, name, volume, creationDate, color, type)
-- values ('Ford', 'Mustang', 3.2, 1993,  'коричневый', 'седан'),
--        ('BMW', 'X5', 4.4, 2025,  'черная', 'SUV');

insert into cars (manufacturer, name, volume, creationDate, color, type)
values
    ('Audi', 'A6', 2.0, 2023, 'синий', 'sedan'),
    ('Toyota', 'Camry', 2.5, 2022, 'белая', 'sedan'),
    ('Ford', 'Mustang', 5.0, 2021, 'красная', 'coupe'),
    ('Lada', 'Vesta', 1.6, 2020, 'серебристая', 'sedan'),
    ('Lada', 'Niva', 1.7, 2019, 'зеленая', 'SUV'),
    ('Geely', 'Atlas', 2.0, 2023, 'черный', 'SUV'),
    ('BYD', 'Song', 1.5, 2022, 'синий', 'crossover'),
    ('Changan', 'CS75', 2.0, 2021, 'белый', 'SUV'),
    ('Mercedes-Benz', 'E-Class', 3.0, 2024, 'серый', 'sedan');

select * from cars